"""Blender-authored rotation bank. Run with blender --background --python this_file.
The .blend is an editable control-rig study, not a replacement for the game mesh.
Coordinates are game-local radians; Blender is used to evaluate animation curves.
"""
import bpy, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
existing = '--export-existing' in sys.argv
if existing:
    bpy.ops.wm.open_mainfile(filepath=str(ROOT/'art/blade/attack-curves.blend'))
else:
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
# shoulder xyz, torso xyz, offhand xyz, elbow x, knee R/L, body pitch, body drop
rest = [-.35,0,.12, 0,0,0, -.46,0,-.32, -.2,.12,.12,0,0]
return_rest = [.92,0,-.38, 0,0,0, -.24,0,-.15, -.3,.18,.1,0,0]
clips = [
 ('opener', .28, [(0,rest),(.18,[-1.85,-.2,.72,-.08,.5,-.08,-.8,.1,-.55,-.65,.25,.12,-.08,-.04]),(.28,[-.25,-.12,.12,.08,.04,-.04,-.48,0,-.25,-.12,.14,.22,.08,-.02]),(.48,[1.08,.06,-.2,.12,-.42,.05,-.3,0,-.16,-.12,.1,.3,.1,0]),(1,return_rest)]),
 ('return', .32, [(0,return_rest),(.22,[.55,.35,-.78,0,-.58,.09,-.24,0,.13,-.35,.15,.3,-.06,-.05]),(.32,[-.5,.08,-.25,.08,-.04,0,-.38,0,-.1,-.1,.25,.15,.06,-.03]),(.56,[-1.85,-.15,.3,0,.5,-.07,-.46,0,-.15,-.25,.3,.1,.08,0]),(1,rest)]),
 ('finisher', .42, [(0,rest),(.3,[-1.65,-.28,.8,-.16,.82,0,-.8,0,-.65,-.6,.42,.4,-.18,-.12]),(.42,[-.2,-.1,-.8,.05,-.12,-.08,-.25,0,.65,-.1,.3,.2,.06,-.07]),(.64,[1.55,.08,-.3,.09,-1.05,.04,-.24,0,-.18,-.1,.14,.3,.12,-.02]),(1,rest)]),
 ('charged', .38, [(0,[-2.2,-.45,.65,-.09,.45,-.08,-1.3,.28,-.3,-.8,.4,.3,-.1,-.07]),(.24,[-2.45,-.35,.3,-.24,.3,0,-1.8,.1,-.25,-1.05,.5,.4,-.2,-.14]),(.38,[-.15,0,.08,.2,0,0,-.3,0,-.45,-.08,.65,.35,.2,-.2]),(.52,[.95,.05,-.08,.3,-.24,0,.3,0,-.5,-.1,.55,.22,.26,-.16]),(1,rest)])]
tracks=[]
for ci,(name,strike,keys) in enumerate(clips):
    controls=[]
    if existing:
        controls=[bpy.data.objects[f'{name}_{i:02}'] for i in range(14)]
    else:
        col=bpy.data.collections.new(name);bpy.context.scene.collection.children.link(col)
        controls=[]
        for i in range(14):
            obj=bpy.data.objects.new(f'{name}_{i:02}',None);col.objects.link(obj)
            obj.empty_display_type='ARROWS';obj.location=(ci*3,i*.18,0)
            for phase,values in keys:
                obj.rotation_euler.x=values[i]
                obj.keyframe_insert(data_path='rotation_euler',index=0,frame=phase*100+1)
            controls.append(obj)
    frames=[]
    for frame in range(101):
        bpy.context.scene.frame_set(frame+1)
        frames.append([round(o.rotation_euler.x,5) for o in controls])
    tracks.append({'name':name,'strikePoint':strike,'frames':frames})
bpy.context.scene.frame_start=1;bpy.context.scene.frame_end=101
bpy.context.scene['purpose']='Blade attack curves; runtime phase follows Combat. No root motion or hitstop.'
if not existing:
    bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/blade/attack-curves.blend'))
out=ROOT/'src/game/bladeMotionData.ts'
out.write_text('// Generated by art/blade/author_motion.py in Blender. Do not hand edit.\nexport const BLADE_MOTION = '+json.dumps(tracks,separators=(',',':'))+';\n',encoding='utf-8')
print('Exported four Blade clips, 101 phase samples each.')
